# Copyright 2026 The Alcy Project Authors
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

source_set("codegen_llvm") {
  sources = [
    "common.cc",
    "common.h",
    "declaration.h",
    "llvm_ir_emitter.cc",
    "llvm_ir_emitter.h",
    "llvm_ir_emitter_compute.cc",
    "llvm_ir_emitter_memory.cc",
    "llvm_ir_storage.h",
    "llvm_object_emitter.cc",
    "llvm_object_emitter.h",
  ]
  deps = [
    "//src:base_modules",
    "//src/diag",
  ]
  public_deps = [
    "//src/ir",
    "//src/symbol",
    "//third_party/llvm",
  ]

  configs += [ "//src:alcy_config" ]
}
