version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "8 7 * * 1"
      timezone: "UTC"
    open-pull-requests-limit: 10

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "8 7 * * 1"
      timezone: "UTC"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "third_party/llvm/src"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "8 7 * * 1"
      timezone: "UTC"
    open-pull-requests-limit: 10
