# Copyright 2026 The Alcy Project Authors
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

source_set("lowering") {
  sources = [
    "lowerer.cc",
    "lowerer.h",
    "lowering.cc",
    "lowering.h",
    "lowering_comp.cc",
    "lowering_expr.cc",
  ]
  deps = [
    "//compiler:base_modules",
    "//compiler/analyzer",
    "//compiler/ast",
    "//compiler/diag",
    "//compiler/i18n",
    "//compiler/ir",
    "//compiler/source",
    "//compiler/text",
  ]
  configs += [ "//compiler:alcy_config" ]
}
