// Copyright 2026 The Alcy Project Authors
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#include "pkg/lock.h"

#include <iterator>
#include <span>
#include <string>
#include <string_view>

#include "fmt/core.h"
#include "fmt/format.h"
#include "fpag/base/numeric.h"
#include "fpag/base/result.h"
#include "fpag/mem/arena.h"
#include "pkg/arena_copy.h"
#include "pkg/manifest.h"
#include "pkg/resolve.h"

namespace pkg {

namespace {

// Length of the well-formed UTF-8 sequence starting at `text[i]`, or 0
// when the bytes there are not one. A path component on POSIX need not
// be valid UTF-8, and a TOML string must be, so the caller escapes
// whatever this rejects.
usize utf8_sequence_length(std::string_view text, usize i) {
  const auto byte = [text](usize at) {
    return static_cast<unsigned char>(text[at]);
  };
  const unsigned char lead = byte(i);
  const auto continuation = [&](usize at) { return (byte(at) & 0xC0) == 0x80; };
  if (lead < 0x80) {
    return 1;
  }
  if ((lead & 0xE0) == 0xC0) {
    return i + 1 < text.size() && continuation(i + 1) ? 2 : 0;
  }
  if ((lead & 0xF0) == 0xE0) {
    return i + 2 < text.size() && continuation(i + 1) && continuation(i + 2)
               ? 3
               : 0;
  }
  if ((lead & 0xF8) == 0xF0) {
    return i + 3 < text.size() && continuation(i + 1) && continuation(i + 2) &&
                   continuation(i + 3)
               ? 4
               : 0;
  }
  // A continuation byte with no lead, or 0xF8-0xFF, starts nothing.
  return 0;
}

void write_escaped(fmt::memory_buffer& out, std::string_view text) {
  static constexpr char HEX[] = "0123456789abcdef";
  for (usize i = 0; i < text.size();) {
    const char c = text[i];
    const unsigned char u = static_cast<unsigned char>(c);
    switch (c) {
      case '"':
        fmt::format_to(std::back_inserter(out), "\\\"");
        ++i;
        continue;
      case '\\':
        fmt::format_to(std::back_inserter(out), "\\\\");
        ++i;
        continue;
      default: break;
    }
    // TOML requires every control character escaped, and 0x7F (DEL)
    // counts.
    if (u < 0x20 || u == 0x7F) {
      fmt::format_to(std::back_inserter(out), "\\u00{}{}", HEX[u >> 4],
                     HEX[u & 0xF]);
      ++i;
      continue;
    }
    // A well-formed multi-byte character passes through as itself; a
    // byte that starts no such sequence is escaped as its code unit
    // rather than written through and producing an unparsable
    // document.
    const usize length = u < 0x80 ? 1 : utf8_sequence_length(text, i);
    if (length == 0) {
      fmt::format_to(std::back_inserter(out), "\\u00{}{}", HEX[u >> 4],
                     HEX[u & 0xF]);
      ++i;
      continue;
    }
    out.append(text.substr(i, length));
    i += length;
  }
}

}  // namespace

base::Result<Lockfile, LockError> lock_resolved(
    std::span<const ResolvedPackage> resolved,
    mem::Arena& arena) {
  for (const ResolvedPackage& package : resolved) {
    if (verify_manifest(package.manifest).is_err()) {
      return base::make_err(LockError::InvalidPackage);
    }
  }
  LockedPackage* const packages =
      resolved.empty() ? nullptr
                       : static_cast<LockedPackage*>(arena.alloc(
                             sizeof(LockedPackage) * resolved.size(),
                             alignof(LockedPackage)));
  for (usize i = 0; i < resolved.size(); ++i) {
    const ResolvedPackage& package = resolved[i];
    // A file URI needs an absolute path: after `//` a relative spelling
    // would read as the authority with an empty path. Path
    // canonicalization is lexical, so a relative input arrives as-is.
    if (!package.dir.is_absolute()) {
      return base::make_err(LockError::InvalidPackage);
    }
    std::string source = "path+file://";
    source += package.dir.as_view();
    packages[i] = LockedPackage{
        .name = copy_str(arena, package.manifest.name),
        .version = package.manifest.version,
        .source = copy_str(arena, source),
    };
  }
  return base::make_ok(Lockfile{
      .packages = packages,
      .package_count = static_cast<u32>(resolved.size()),
  });
}

base::Result<void, LockError> serialize_lockfile(const Lockfile& lock,
                                                 fmt::memory_buffer& out) {
  // Validate everything before the first byte lands in `out`, so a
  // failed call never leaves a half-written lockfile.
  if (lock.package_count > 0 && lock.packages == nullptr) {
    return base::make_err(LockError::InvalidLockfile);
  }
  for (u32 i = 0; i < lock.package_count; ++i) {
    if (lock.packages[i].name.empty()) {
      return base::make_err(LockError::InvalidPackage);
    }
  }
  fmt::format_to(std::back_inserter(out),
                 "# Generated by alcy. Do not edit.\nversion = 1\n");
  for (u32 i = 0; i < lock.package_count; ++i) {
    const LockedPackage& package = lock.packages[i];
    fmt::format_to(std::back_inserter(out), "\n[[package]]\nname = \"");
    write_escaped(out, package.name);
    fmt::format_to(
        std::back_inserter(out), "\"\nversion = \"{}.{}.{}\"\nsource = \"",
        package.version.major, package.version.minor, package.version.patch);
    write_escaped(out, package.source);
    fmt::format_to(std::back_inserter(out), "\"\n");
  }
  return base::make_ok();
}

}  // namespace pkg
