# Copyright 2026 The Alcy Project Authors
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

source_set("parser") {
  sources = [
    "desugar.cc",
    "desugar.h",
    "parser.cc",
    "parser.h",
    "parser_expr.cc",
    "parser_type.cc",
  ]
  deps = [
    "//src:base_modules",
    "//src/ast",
    "//src/diag",
    "//src/lexer",
    "//src/source",
  ]
  configs += [ "//src:alcy_config" ]
}
