// Copyright 2026 The Alcy Project Authors
// This source code is licensed under the Apache License, Version 2.0 with LLVM
// Exceptions which can be found in the LICENSE file.

#include "pkg/lock.h"

#include <string>
#include <string_view>
#include <utility>
#include <vector>

#include "diag/bag.h"
#include "doctest/doctest.h"
#include "fmt/format.h"
#include "fpag/mem/arena.h"
#include "pkg/resolve.h"
#include "source/source.h"
#include "tests/util/test_fs.h"

namespace pkg {

namespace {

struct Fixture {
  mem::Arena arena;
  diag::DiagBag bag{arena};
  source::SourceManager sources;

  Fixture() { arena.reserve(1u << 20); }
};

}  // namespace

TEST_CASE("Lockfile round-trips through resolve output") {
  test_fs::TempDir dir("alcy_lock_test");
  constexpr std::string_view manifest =
      "[package]\n"
      "name = \"app\"\n"
      "version = \"1.2.3\"\n"
      "\n"
      "[dependencies]\n"
      "dep = { path = \"dep\" }\n";
  const bool setup =
      dir.write_file("app/alcy.toml", manifest) &&
      dir.write_file("app/dep/alcy.toml",
                     "[package]\nname = \"dep\"\nversion = \"0.0.1\"\n");
  CHECK(setup);
  if (!setup) {
    return;
  }

  Fixture f;
  diag::Fallible<std::vector<ResolvedPackage>> resolved =
      resolve_package(dir.join("app"), f.sources, f.arena, f.bag);
  CHECK(resolved.is_ok());
  if (!resolved.is_ok()) {
    return;
  }

  const Lockfile lock = lock_resolved(std::move(resolved).unwrap(), f.arena);
  CHECK(lock.package_count == 2);
  if (lock.package_count != 2) {
    return;
  }

  fmt::memory_buffer out;
  serialize_lockfile(lock, out);
  const std::string text(out.data(), out.size());
  const std::string expected =
      "# Generated by alcy. Do not edit.\n"
      "version = 1\n"
      "\n"
      "[[package]]\n"
      "name = \"app\"\n"
      "version = \"1.2.3\"\n"
      "source = \"path+file://" +
      dir.join("app") +
      "\"\n"
      "\n"
      "[[package]]\n"
      "name = \"dep\"\n"
      "version = \"0.0.1\"\n"
      "source = \"path+file://" +
      dir.join("app") + "/dep\"\n";
  CHECK(text == expected);
}

TEST_CASE("Lockfile escapes special characters") {
  const LockedPackage packages[] = {
      {.name = "quote\"back\\slash",
       .version = {0, 0, 0},
       .source = "path+file:///x"},
  };
  const Lockfile lock{.packages = packages, .package_count = 1};

  fmt::memory_buffer out;
  serialize_lockfile(lock, out);
  const std::string text(out.data(), out.size());
  CHECK(text.find("name = \"quote\\\"back\\\\slash\"") != std::string::npos);
}

}  // namespace pkg
