// Copyright 2026 The Alcy Project Authors
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#include "pkg/lock.h"

#include <string>
#include <string_view>
#include <utility>
#include <vector>

#include "diag/bag.h"
#include "doctest/doctest.h"
#include "fmt/format.h"
#include "fpag/io/temp_dir.h"
#include "fpag/mem/arena.h"
#include "path/path.h"
#include "pkg/resolve.h"
#include "source/source.h"

namespace pkg {

namespace {

struct Fixture {
  mem::Arena arena;
  diag::DiagBag bag{arena};
  source::SourceManager sources;

  Fixture() { arena.reserve(1u << 20); }
};

}  // namespace

TEST_CASE("Lockfile round-trips through resolve output") {
  io::TempDir dir = io::TempDir::create_unique("alcy_lock_test_");
  constexpr std::string_view manifest =
      "[package]\n"
      "name = \"app\"\n"
      "version = \"1.2.3\"\n"
      "\n"
      "[dependencies]\n"
      "dep = { path = \"dep\" }\n";
  const bool setup =
      dir.write_file("cli/alcy.toml", manifest) &&
      dir.write_file("cli/dep/alcy.toml",
                     "[package]\nname = \"dep\"\nversion = \"0.0.1\"\n");
  CHECK(setup);
  if (!setup) {
    return;
  }

  Fixture f;
  base::Result<std::vector<ResolvedPackage>, diag::Reported> resolved =
      resolve_package(dir.join("cli"), f.sources, f.arena, f.bag);
  CHECK(resolved.is_ok());
  if (!resolved.is_ok()) {
    return;
  }

  base::Result<Lockfile, LockError> locked =
      lock_resolved(std::move(resolved).unwrap(), f.arena);
  CHECK(locked.is_ok());
  if (locked.is_err()) {
    return;
  }
  const Lockfile lock = std::move(locked).unwrap();
  CHECK(lock.package_count == 2);
  if (lock.package_count != 2) {
    return;
  }

  fmt::memory_buffer out;
  base::Result<void, LockError> serialized = serialize_lockfile(lock, out);
  CHECK(serialized.is_ok());
  const std::string text(out.data(), out.size());
  const std::string expected =
      "# Generated by alcy. Do not edit.\n"
      "version = 1\n"
      "\n"
      "[[package]]\n"
      "name = \"app\"\n"
      "version = \"1.2.3\"\n"
      "source = \"path+file://" +
      dir.join("cli") +
      "\"\n"
      "\n"
      "[[package]]\n"
      "name = \"dep\"\n"
      "version = \"0.0.1\"\n"
      "source = \"path+file://" +
      dir.join("cli") + "/dep\"\n";
  CHECK(text == expected);
}

TEST_CASE("Lockfile escapes special characters") {
  const LockedPackage packages[] = {
      {.name = "quote\"back\\slash",
       .version = {0, 0, 0},
       .source = "path+file:///x"},
  };
  const Lockfile lock{.packages = packages, .package_count = 1};

  fmt::memory_buffer out;
  base::Result<void, LockError> serialized = serialize_lockfile(lock, out);
  CHECK(serialized.is_ok());
  const std::string text(out.data(), out.size());
  CHECK(text.find("name = \"quote\\\"back\\\\slash\"") != std::string::npos);
}

TEST_CASE("Lockfile rejects structurally invalid input") {
  const Lockfile bad{.packages = nullptr, .package_count = 2};
  fmt::memory_buffer out;
  CHECK(serialize_lockfile(bad, out).is_err());
  CHECK(out.size() == 0);

  const LockedPackage anonymous[] = {
      {.name = "", .version = {0, 0, 0}, .source = "path+file:///x"},
  };
  const Lockfile unnamed{.packages = anonymous, .package_count = 1};
  fmt::memory_buffer unnamed_out;
  CHECK(serialize_lockfile(unnamed, unnamed_out).is_err());
  CHECK(unnamed_out.size() == 0);
}

TEST_CASE("lock_resolved rejects a package with an invalid manifest") {
  Fixture f;
  // An empty package name fails manifest verification.
  const ResolvedPackage bad{
      .manifest = {},
      .dir = path::Path::from_native("/x").unwrap(),
  };
  base::Result<Lockfile, LockError> locked = lock_resolved({&bad, 1}, f.arena);
  CHECK(locked.is_err());
}

}  // namespace pkg
