# Copyright 2026 The Alcy Project Authors
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

source_set("lower") {
  sources = [
    "lower.cc",
    "lower.h",
    "lower_comp.cc",
    "lower_expr.cc",
    "lowerer.h",
  ]
  deps = [
    "//src:base_modules",
    "//src/analyzer",
    "//src/ast",
    "//src/diag",
    "//src/ir",
    "//src/source",
  ]
  configs += [ "//src:alcy_config" ]
}
