# Copyright 2026 The Alcy Project Authors
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

source_set("analyzer") {
  sources = [
    "checker.h",
    "fmt.h",
    "resolve.cc",
    "resolve.h",
    "types.cc",
    "types.h",
    "types_expr.cc",
  ]
  deps = [
    "//src:base_modules",
    "//src/ast",
    "//src/diag",
    "//src/ir",
    "//src/lexer",
    "//src/parser",
    "//src/path",
    "//src/source",
  ]
  configs += [ "//src:alcy_config" ]
}
