# Copyright 2026 The Alcy Project Authors
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

source_set("ir") {
  sources = [
    "binary_format.h",
    "block.cc",
    "block.h",
    "block_param.cc",
    "block_param.h",
    "common.cc",
    "common.h",
    "deserialize.cc",
    "deserialize.h",
    "external_function.cc",
    "external_function.h",
    "formatter.cc",
    "formatter.h",
    "function.cc",
    "function.h",
    "immutable.cc",
    "immutable.h",
    "instruction.cc",
    "instruction.h",
    "instruction_flags.cc",
    "instruction_flags.h",
    "opcode.cc",
    "opcode.h",
    "operand.cc",
    "operand.h",
    "register.cc",
    "register.h",
    "seq_builder.cc",
    "seq_builder.h",
    "serialize.cc",
    "serialize.h",
    "storage.cc",
    "storage.h",
    "storage_builder.cc",
    "storage_builder.h",
    "text_dump.cc",
    "text_dump.h",
    "type.cc",
    "type.h",
    "type_util.cc",
    "type_util.h",
    "verifier.cc",
    "verifier.h",
    "write_input.h",
  ]
  deps = [
    "//compiler:base_modules",
    "//compiler/diag",
    "//third_party/fmt",
  ]
  configs += [ "//compiler:alcy_config" ]
}
