# Copyright 2026 The Alcy Project Authors
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

source_set("codegen") {
  sources = [
    "backend.cc",
    "backend.h",
    "diag_code.h",
    "target.cc",
    "target.h",
    "x86_emitter.cc",
  ]
  deps = [
    "//compiler:base_modules",
    "//compiler/diag",
    "//compiler/ir",
  ]
  configs += [ "//compiler:alcy_config" ]
}
