# Copyright 2026 The Alcy Project Authors
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

source_set("ir") {
  sources = [
    "block.h",
    "block_param.h",
    "common.h",
    "external_function.h",
    "formatter.h",
    "function.h",
    "immutable.h",
    "instruction.h",
    "instruction_flags.h",
    "opcode.h",
    "operand.h",
    "register.h",
    "seq_builder.h",
    "storage.cc",
    "storage.h",
    "storage_builder.cc",
    "storage_builder.h",
    "type.h",
    "type_util.h",
    "verifier.cc",
    "verifier.h",
  ]
  deps = [
    "//src:base_modules",
    "//src/diag",
  ]
  configs += [ "//src:alcy_config" ]
}
