# Copyright 2026 The Alcy Project Authors
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

source_set("pkg") {
  sources = [
    "lock.cc",
    "lock.h",
    "manifest.cc",
    "manifest.h",
    "modules.cc",
    "modules.h",
    "resolve.cc",
    "resolve.h",
  ]
  deps = [
    "//src:base_modules",
    "//src/diag",
    "//src/path",
    "//src/source",
    "//third_party/toml",
  ]
  configs += [ "//src:alcy_config" ]
}
