// Copyright 2026 The Alcy Project Authors
// This source code is licensed under the Apache License, Version 2.0 with LLVM
// Exceptions which can be found in the LICENSE file.

#include "pkg/lock.h"

#include <iterator>
#include <span>
#include <string>
#include <string_view>

#include "fmt/core.h"
#include "fmt/format.h"
#include "fpag/base/numeric.h"
#include "fpag/mem/arena.h"
#include "pkg/manifest.h"
#include "pkg/resolve.h"

namespace pkg {

namespace {

std::string_view copy_str(mem::Arena& arena, std::string_view bytes) {
  if (bytes.empty()) {
    return {};
  }
  char* const mem =
      static_cast<char*>(arena.alloc(bytes.size(), alignof(char)));
  for (usize i = 0; i < bytes.size(); ++i) {
    mem[i] = bytes[i];
  }
  return {mem, bytes.size()};
}

void write_escaped(fmt::memory_buffer& out, std::string_view text) {
  static constexpr char kHex[] = "0123456789abcdef";
  for (const char c : text) {
    switch (c) {
      case '"': fmt::format_to(std::back_inserter(out), "\\\""); break;
      case '\\': fmt::format_to(std::back_inserter(out), "\\\\"); break;
      default:
        if (c >= 0x00 && c < 0x20) {
          const unsigned char u = static_cast<unsigned char>(c);
          fmt::format_to(std::back_inserter(out), "\\u00{}{}", kHex[u >> 4],
                         kHex[u & 0xF]);
        } else {
          out.push_back(c);
        }
        break;
    }
  }
}

}  // namespace

Lockfile lock_resolved(std::span<const ResolvedPackage> resolved,
                       mem::Arena& arena) {
  LockedPackage* const packages =
      resolved.empty() ? nullptr
                       : static_cast<LockedPackage*>(arena.alloc(
                             sizeof(LockedPackage) * resolved.size(),
                             alignof(LockedPackage)));
  for (usize i = 0; i < resolved.size(); ++i) {
    const ResolvedPackage& package = resolved[i];
    std::string source = "path+file://";
    source += package.dir.as_view();
    packages[i] = LockedPackage{
        .name = copy_str(arena, package.manifest.name),
        .version = package.manifest.version,
        .source = copy_str(arena, source),
    };
  }
  return {.packages = packages,
          .package_count = static_cast<u32>(resolved.size())};
}

void serialize_lockfile(const Lockfile& lock, fmt::memory_buffer& out) {
  fmt::format_to(std::back_inserter(out),
                 "# Generated by alcy. Do not edit.\nversion = 1\n");
  for (u32 i = 0; i < lock.package_count; ++i) {
    const LockedPackage& package = lock.packages[i];
    fmt::format_to(std::back_inserter(out), "\n[[package]]\nname = \"");
    write_escaped(out, package.name);
    fmt::format_to(
        std::back_inserter(out), "\"\nversion = \"{}.{}.{}\"\nsource = \"",
        package.version.major, package.version.minor, package.version.patch);
    write_escaped(out, package.source);
    fmt::format_to(std::back_inserter(out), "\"\n");
  }
}

}  // namespace pkg
