name: Build WebAssembly

on:
  workflow_call:
    inputs:
      build_type:
        required: true
        type: string
      role:
        description: "Build role ('ci' or 'release')"
        required: false
        default: "ci"
        type: string

jobs:
  build:
    name: WebAssembly (${{ inputs.build_type }})
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false

    env:
      COLORTERM: 256color

    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Setup Emscripten
        uses: emscripten-core/setup-emsdk@4528d102f7230f0e7b276855c01ea1159be0e984

      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6
        with:
          bun-version: 1.4.2

      - name: Setup GN
        uses: pug523/actions/setup-gn@e4abb74456e529372bb1b7ebb71db1b647be3fd1

      - name: Install Ninja
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends ninja-build

      - name: Install uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4
        with:
          enable-cache: true

      - name: Setup Python Virtual Environment
        run: |
          uv python install
          uv sync --frozen
          echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH

      - name: Cache Build Directory
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          path: out/build
          key: ${{ runner.os }}-wasm-wasm32-${{ inputs.build_type }}-${{ inputs.role }}-false-build-dir

      - name: Build All
        shell: bash
        run: uv run ./build/scripts/build.py --target=all --mode=${{ inputs.build_type }} --build-subdir=build --target-os=emscripten

      - name: Upload Intermediates for Debug
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: wasm-build-out-wasm32-${{ inputs.build_type }}
          path: out/build/
          retention-days: 1

      - name: Run Tests
        shell: bash
        run: uv run ./build/scripts/run.py --target=tests --mode=${{ inputs.build_type }} --build-subdir=build --target-os=emscripten

      - name: Package & Generate Checksum
        shell: bash
        run: |
          uv run python ./build/scripts/package.py \
            --plat=wasm \
            --arch=wasm32 \
            --mode="${{ inputs.build_type }}" \
            --role="${{ inputs.role }}" \
            --archive=tar.zst

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: wasm-wasm32-${{ inputs.build_type }}
          path: |
            *.tar.zst
            *.sha256
          if-no-files-found: error
